name: "auto-release"
description: "Automatically draft release notes for your next release as Pull Requests are merged into main. Optionally, automatically publish a release for every Pull Request."
inputs:
  token:
    description: "Standard GitHub token (e.g., secrets.GITHUB_TOKEN)"
    required: false
  publish:
    description: "Whether to publish a new release immediately"
    required: false
    default: true
  prerelease:
    description: "Boolean indicating whether this release should be a prerelease"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    # Checkout current commit in calling repo
    - name: "Checkout commit"
      uses: actions/checkout@v2

    # Get PR from merged commit to master so we can leverage some of the meta data, including labels
    - uses: actions-ecosystem/action-get-merged-pull-request@v1
      id: get-merged-pull-request
      with:
        github_token: ${{ inputs.token }}

    # Drafts the next Release and compiles the notes as Pull Requests are merged into "main" (unless the `no-release` label is used on the PR)
    - uses: release-drafter/release-drafter@v5.20.0
      with:
        publish: ${{ inputs.publish || !contains(steps.get-merged-pull-request.outputs.labels, 'no-release') }}
        prerelease: ${{ inputs.prerelease }}
        config-name: auto-release-config.yml
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
