name: "auto-release-reusable"
on:
  workflow_call:
    inputs:
      publish:
        description: "Flag indicating whether to create a new release immediately (true) or just add changes to release draft (false)"
        type: boolean
        required: false
        default: true
      prerelease:
        description: "Flag indicating whether this release should be a prerelease (true) or a standard release (false)"
        type: boolean
        required: false
        default: false
    secrets:
      token:
        description: "Standard GitHub token used for creating new release (passing in secrets.GITHUB_TOKEN would be sufficient)"

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/github-action-auto-release@v1.12.0
      with:
        prerelease: ${{ inputs.prerelease }}
        publish: ${{ inputs.publish }}
        token: ${{ secrets.token }}
